// Demo dataset distilled from a real 14-day Pulse export (2026-07-10 → 07-24).
// Stars are curated journal moments; pulses are check-ins rendered as dust and
// deliberately carry NO note text — times, categories, and ratings only.
// Generated by scripts in the repo history — edit by regenerating, not by hand.

export const DEMO_ENTRIES = [
  {
    "id": "d01",
    "title": "Ribeye night with Utku",
    "category": "Eat & Drink",
    "importance": 6,
    "boost": 0,
    "summary": "Late night cooking ribeye with Utku — came off perfect, medium rare.",
    "status": "open",
    "raw": "Late night cooking ribeye with Utku — came off perfect, medium rare.",
    "createdAt": "2026-07-11T19:00:02Z"
  },
  {
    "id": "d02",
    "title": "Road House afternoon",
    "category": "Watch",
    "importance": 3,
    "boost": 0,
    "summary": "Lazy Saturday watching Road House.",
    "status": "open",
    "raw": "Lazy Saturday watching Road House.",
    "createdAt": "2026-07-11T20:26:53Z"
  },
  {
    "id": "d03",
    "title": "England vs Norway with Utku",
    "category": "Friends",
    "importance": 6,
    "boost": 0,
    "summary": "World Cup match with Utku, badass club sandwich from the bodega. Life is good.",
    "status": "open",
    "raw": "World Cup match with Utku, badass club sandwich from the bodega. Life is good.",
    "createdAt": "2026-07-11T21:44:27Z"
  },
  {
    "id": "d04",
    "title": "Pick up Meredith from airport",
    "category": "To Do",
    "importance": 5,
    "boost": 0,
    "summary": "Meredith lands at 5:46 — airport pickup.",
    "status": "done",
    "raw": "Meredith lands at 5:46 — airport pickup.",
    "createdAt": "2026-07-12T17:05:58Z",
    "resolvedBy": "d05"
  },
  {
    "id": "d05",
    "title": "Airport pickup, dinner at BJ's",
    "category": "To Do",
    "importance": 4,
    "boost": 0,
    "summary": "Picked Meredith up from the airport, dinner at BJ's.",
    "status": "open",
    "raw": "Picked Meredith up from the airport, dinner at BJ's.",
    "createdAt": "2026-07-13T03:10:12Z",
    "resolvesId": "d04"
  },
  {
    "id": "d06",
    "title": "Tennis with Jacob",
    "category": "Sports",
    "importance": 6,
    "boost": 0,
    "summary": "Hour and a half with Jacob — not our best, still a good workout.",
    "status": "open",
    "raw": "Hour and a half with Jacob — not our best, still a good workout.",
    "createdAt": "2026-07-14T02:13:30Z"
  },
  {
    "id": "d07",
    "title": "Werner leasing presentation",
    "category": "Work",
    "importance": 7,
    "boost": 0,
    "summary": "Leasing presentation for Werner needs to get done.",
    "status": "done",
    "raw": "Leasing presentation for Werner needs to get done.",
    "createdAt": "2026-07-13T16:07:43Z",
    "resolvedBy": "d08"
  },
  {
    "id": "d08",
    "title": "Leasing deck done on the bus",
    "category": "Work",
    "importance": 5,
    "boost": 0,
    "summary": "Focused on the bus ride back from Andy's and finished the Werner deck.",
    "status": "open",
    "raw": "Focused on the bus ride back from Andy's and finished the Werner deck.",
    "createdAt": "2026-07-14T16:50:05Z",
    "resolvesId": "d07"
  },
  {
    "id": "d09",
    "title": "RPG math game",
    "category": "Ideas",
    "importance": 8,
    "boost": 2,
    "summary": "Claude project: an RPG math game. It's actually looking kind of good.",
    "status": "open",
    "raw": "Claude project: an RPG math game. It's actually looking kind of good.",
    "createdAt": "2026-07-14T23:54:48Z"
  },
  {
    "id": "d10",
    "title": "Sub-teaching onboarding + I-9s",
    "category": "To Do",
    "importance": 6,
    "boost": 0,
    "summary": "Substitute teacher onboarding paperwork — I-9 forms nearly figured out.",
    "status": "done",
    "raw": "Substitute teacher onboarding paperwork — I-9 forms nearly figured out.",
    "createdAt": "2026-07-15T21:31:17Z",
    "resolvedBy": "d11"
  },
  {
    "id": "d11",
    "title": "Finished swing onboarding",
    "category": "To Do",
    "importance": 5,
    "boost": 0,
    "summary": "Completed all the swing substitute-teacher onboarding I'd been procrastinating.",
    "status": "open",
    "raw": "Completed all the swing substitute-teacher onboarding I'd been procrastinating.",
    "createdAt": "2026-07-16T17:35:28Z",
    "resolvesId": "d10"
  },
  {
    "id": "d12",
    "title": "Open-art iPhone wallpaper app",
    "category": "Ideas",
    "importance": 5,
    "boost": 0,
    "summary": "Claude app idea: turn open-source art into iPhone wallpaper collections.",
    "status": "open",
    "raw": "Claude app idea: turn open-source art into iPhone wallpaper collections.",
    "createdAt": "2026-07-16T21:53:54Z"
  },
  {
    "id": "d13",
    "title": "Tennis — good winners",
    "category": "Sports",
    "importance": 7,
    "boost": 0,
    "summary": "Great session with Jacob, hit real winners. Yamo noodles after.",
    "status": "open",
    "raw": "Great session with Jacob, hit real winners. Yamo noodles after.",
    "createdAt": "2026-07-17T03:03:49Z"
  },
  {
    "id": "d14",
    "title": "Book the glamping trip",
    "category": "To Do",
    "importance": 6,
    "boost": 0,
    "summary": "About to book the gold-country glamping site for the weekend.",
    "status": "done",
    "raw": "About to book the gold-country glamping site for the weekend.",
    "createdAt": "2026-07-16T22:45:33Z",
    "resolvedBy": "d15"
  },
  {
    "id": "d15",
    "title": "On the road to gold country",
    "category": "To Do",
    "importance": 5,
    "boost": 0,
    "summary": "Packed, groceries done, driving to the glamping spot with Meredith.",
    "status": "open",
    "raw": "Packed, groceries done, driving to the glamping spot with Meredith.",
    "createdAt": "2026-07-18T00:41:22Z",
    "resolvesId": "d14"
  },
  {
    "id": "d16",
    "title": "Brewery stop: beers & hot dogs",
    "category": "Eat & Drink",
    "importance": 5,
    "boost": 0,
    "summary": "The brewery near Sacramento we love — a round and hot dogs before the last stretch.",
    "status": "open",
    "raw": "The brewery near Sacramento we love — a round and hot dogs before the last stretch.",
    "createdAt": "2026-07-18T03:08:02Z"
  },
  {
    "id": "d17",
    "title": "Finish the monthly report",
    "category": "To Do",
    "importance": 6,
    "boost": 0,
    "summary": "Monthly report still hanging over the week.",
    "status": "open",
    "raw": "Monthly report still hanging over the week.",
    "createdAt": "2026-07-17T16:35:09Z"
  },
  {
    "id": "d18",
    "title": "Reading Martyr!",
    "category": "Watch",
    "importance": 4,
    "boost": 0,
    "summary": "Slowly making my way through Martyr.",
    "status": "open",
    "raw": "Slowly making my way through Martyr.",
    "createdAt": "2026-07-17T16:35:09Z"
  },
  {
    "id": "d19",
    "title": "Bakery + the Polish family",
    "category": "On My Mind",
    "importance": 7,
    "boost": 0,
    "summary": "Amazing bakery in gates valley; long talk with a family from Poland doing three weeks across the US. Left me energized — I love these interactions.",
    "status": "open",
    "raw": "Amazing bakery in gates valley; long talk with a family from Poland doing three weeks across the US. Left me energized — I love these interactions.",
    "createdAt": "2026-07-20T17:42:33Z"
  },
  {
    "id": "d20",
    "title": "First tennis lesson in the Sunset",
    "category": "Sports",
    "importance": 6,
    "boost": 0,
    "summary": "Booked a 4:30 lesson in the Sunset — excited and a little nervous about the cost.",
    "status": "done",
    "raw": "Booked a 4:30 lesson in the Sunset — excited and a little nervous about the cost.",
    "createdAt": "2026-07-20T22:29:26Z",
    "resolvedBy": "d21"
  },
  {
    "id": "d21",
    "title": "Tennis lesson was great",
    "category": "Sports",
    "importance": 6,
    "boost": 0,
    "summary": "The lesson was very good and engaging. Burger and a beer after, Waymo home.",
    "status": "open",
    "raw": "The lesson was very good and engaging. Burger and a beer after, Waymo home.",
    "createdAt": "2026-07-21T02:08:25Z",
    "resolvesId": "d20"
  },
  {
    "id": "d22",
    "title": "The Hawk on Netflix",
    "category": "Watch",
    "importance": 3,
    "boost": 0,
    "summary": "Watching The Hawk with Will Ferrell.",
    "status": "open",
    "raw": "Watching The Hawk with Will Ferrell.",
    "createdAt": "2026-07-20T23:58:29Z"
  },
  {
    "id": "d23",
    "title": "Why can't I make myself study?",
    "category": "On My Mind",
    "importance": 9,
    "boost": 3,
    "summary": "The recurring one: teacher exams in physics and math, and I procrastinate with all my might. Why?",
    "status": "open",
    "raw": "The recurring one: teacher exams in physics and math, and I procrastinate with all my might. Why?",
    "createdAt": "2026-07-20T23:58:30Z"
  },
  {
    "id": "d24",
    "title": "Why am I not training for a triathlon?",
    "category": "On My Mind",
    "importance": 7,
    "boost": 0,
    "summary": "The question that keeps coming back on low days.",
    "status": "open",
    "raw": "The question that keeps coming back on low days.",
    "createdAt": "2026-07-21T20:16:49Z"
  },
  {
    "id": "d25",
    "title": "Entrepreneurship came easy in college",
    "category": "On My Mind",
    "importance": 8,
    "boost": 0,
    "summary": "I'd just do entrepreneur stuff in college like a superpower. Why could I follow through then but not now?",
    "status": "open",
    "raw": "I'd just do entrepreneur stuff in college like a superpower. Why could I follow through then but not now?",
    "createdAt": "2026-07-22T16:04:50Z"
  },
  {
    "id": "d26",
    "title": "Surf on Friday",
    "category": "To Do",
    "importance": 5,
    "boost": 0,
    "summary": "Thinking of going surfing — definitely Friday.",
    "status": "open",
    "raw": "Thinking of going surfing — definitely Friday.",
    "createdAt": "2026-07-22T16:04:51Z"
  },
  {
    "id": "d27",
    "title": "Russell's cultural-immersion dinners",
    "category": "Ideas",
    "importance": 6,
    "boost": 0,
    "summary": "Brainstormed with Russell (in Croatia): get locals to cook you dinner for real cultural immersion.",
    "status": "open",
    "raw": "Brainstormed with Russell (in Croatia): get locals to cook you dinner for real cultural immersion.",
    "createdAt": "2026-07-22T21:03:34Z"
  },
  {
    "id": "d28",
    "title": "Cross-country bike trip with Russell",
    "category": "Ideas",
    "importance": 7,
    "boost": 0,
    "summary": "How likely is it Russell and I actually do a cross-country bicycle trip?",
    "status": "open",
    "raw": "How likely is it Russell and I actually do a cross-country bicycle trip?",
    "createdAt": "2026-07-22T21:03:35Z"
  },
  {
    "id": "d29",
    "title": "Branzino night with Utku",
    "category": "Eat & Drink",
    "importance": 6,
    "boost": 0,
    "summary": "Made the fish market right before close — branzino to cook with Utku.",
    "status": "open",
    "raw": "Made the fish market right before close — branzino to cook with Utku.",
    "createdAt": "2026-07-23T01:44:09Z"
  },
  {
    "id": "d30",
    "title": "What does respect mean to me?",
    "category": "On My Mind",
    "importance": 6,
    "boost": 0,
    "summary": "Respect — what does that actually mean to you?",
    "status": "open",
    "raw": "Respect — what does that actually mean to you?",
    "createdAt": "2026-07-23T01:44:10Z"
  }
];

export const DEMO_PULSES = [
  {
    "id": "p1",
    "t": "2026-07-11T00:10:34.965708+00:00",
    "category": "Watch",
    "mood": 6,
    "engagement": 6
  },
  {
    "id": "p2",
    "t": "2026-07-11T19:00:02.880103+00:00",
    "category": "Watch",
    "mood": 7,
    "engagement": 7
  },
  {
    "id": "p3",
    "t": "2026-07-11T20:26:53.211139+00:00",
    "category": "Watch",
    "mood": 9,
    "engagement": 9
  },
  {
    "id": "p4",
    "t": "2026-07-11T21:21:09.58315+00:00",
    "category": "Watch",
    "mood": 6,
    "engagement": 5
  },
  {
    "id": "p5",
    "t": "2026-07-11T21:44:27.771655+00:00",
    "category": "Watch",
    "mood": 9,
    "engagement": 8
  },
  {
    "id": "p6",
    "t": "2026-07-12T00:14:56.535187+00:00",
    "category": "Watch",
    "mood": 7,
    "engagement": 9
  },
  {
    "id": "p7",
    "t": "2026-07-12T01:07:37.764721+00:00",
    "category": "Watch",
    "mood": 10,
    "engagement": 9
  },
  {
    "id": "p8",
    "t": "2026-07-12T17:05:58.229821+00:00",
    "category": "Watch",
    "mood": 3,
    "engagement": 3
  },
  {
    "id": "p9",
    "t": "2026-07-12T18:44:01.548056+00:00",
    "category": "Watch",
    "mood": 4,
    "engagement": 5
  },
  {
    "id": "p10",
    "t": "2026-07-12T20:45:58.639261+00:00",
    "category": "Watch",
    "mood": 3,
    "engagement": 3
  },
  {
    "id": "p11",
    "t": "2026-07-12T21:05:24.499144+00:00",
    "category": "Watch",
    "mood": 4,
    "engagement": 7
  },
  {
    "id": "p12",
    "t": "2026-07-13T03:10:12.098942+00:00",
    "category": "Watch",
    "mood": 8,
    "engagement": 8
  },
  {
    "id": "p13",
    "t": "2026-07-13T16:07:43.049445+00:00",
    "category": "Work",
    "mood": 4,
    "engagement": 6
  },
  {
    "id": "p14",
    "t": "2026-07-13T16:45:01.70783+00:00",
    "category": "On My Mind",
    "mood": 4,
    "engagement": 4
  },
  {
    "id": "p15",
    "t": "2026-07-13T23:36:57.210403+00:00",
    "category": "Watch",
    "mood": 3,
    "engagement": 3
  },
  {
    "id": "p16",
    "t": "2026-07-14T02:13:30.997925+00:00",
    "category": "Sports",
    "mood": 7,
    "engagement": 8
  },
  {
    "id": "p17",
    "t": "2026-07-14T16:50:05.986932+00:00",
    "category": "Work",
    "mood": 6,
    "engagement": 8
  },
  {
    "id": "p18",
    "t": "2026-07-14T17:45:05.0497+00:00",
    "category": "Work",
    "mood": 4,
    "engagement": 8
  },
  {
    "id": "p19",
    "t": "2026-07-14T18:30:11.814375+00:00",
    "category": "Work",
    "mood": 6,
    "engagement": 9
  },
  {
    "id": "p20",
    "t": "2026-07-14T19:01:15.658804+00:00",
    "category": "On My Mind",
    "mood": 4,
    "engagement": 4
  },
  {
    "id": "p21",
    "t": "2026-07-14T19:45:11.876957+00:00",
    "category": "On My Mind",
    "mood": 2,
    "engagement": 1
  },
  {
    "id": "p22",
    "t": "2026-07-14T20:36:12.331848+00:00",
    "category": "On My Mind",
    "mood": 3,
    "engagement": 6
  },
  {
    "id": "p23",
    "t": "2026-07-14T22:01:19.06982+00:00",
    "category": "On My Mind",
    "mood": 4,
    "engagement": 4
  },
  {
    "id": "p24",
    "t": "2026-07-14T23:54:48.270043+00:00",
    "category": "On My Mind",
    "mood": 7,
    "engagement": 7
  },
  {
    "id": "p25",
    "t": "2026-07-15T01:58:47.095899+00:00",
    "category": "Friends",
    "mood": 7,
    "engagement": 9
  },
  {
    "id": "p26",
    "t": "2026-07-15T15:35:56.206317+00:00",
    "category": "On My Mind",
    "mood": 8,
    "engagement": 9
  },
  {
    "id": "p27",
    "t": "2026-07-15T16:54:17.236437+00:00",
    "category": "On My Mind",
    "mood": 7,
    "engagement": 8
  },
  {
    "id": "p28",
    "t": "2026-07-15T17:54:10.296877+00:00",
    "category": "Work",
    "mood": 5,
    "engagement": 10
  },
  {
    "id": "p29",
    "t": "2026-07-15T18:33:59.653586+00:00",
    "category": "On My Mind",
    "mood": 7,
    "engagement": 10
  },
  {
    "id": "p30",
    "t": "2026-07-15T19:20:54.711348+00:00",
    "category": "Work",
    "mood": 7,
    "engagement": 9
  },
  {
    "id": "p31",
    "t": "2026-07-15T20:25:20.783978+00:00",
    "category": "Work",
    "mood": 7,
    "engagement": 9
  },
  {
    "id": "p32",
    "t": "2026-07-15T21:05:48.502926+00:00",
    "category": "Work",
    "mood": 7,
    "engagement": 9
  },
  {
    "id": "p33",
    "t": "2026-07-15T21:31:17.626133+00:00",
    "category": "Friends",
    "mood": 7,
    "engagement": 7
  },
  {
    "id": "p34",
    "t": "2026-07-15T22:42:21.339136+00:00",
    "category": "Friends",
    "mood": 9,
    "engagement": 7
  },
  {
    "id": "p35",
    "t": "2026-07-15T22:55:02.042279+00:00",
    "category": "Friends",
    "mood": 8,
    "engagement": 9
  },
  {
    "id": "p36",
    "t": "2026-07-16T17:35:28.006606+00:00",
    "category": "Work",
    "mood": 7,
    "engagement": 9
  },
  {
    "id": "p37",
    "t": "2026-07-16T18:33:24.859188+00:00",
    "category": "Work",
    "mood": 6,
    "engagement": 8
  },
  {
    "id": "p38",
    "t": "2026-07-16T20:27:10.725931+00:00",
    "category": "On My Mind",
    "mood": 4,
    "engagement": 2
  },
  {
    "id": "p39",
    "t": "2026-07-16T21:02:41.538495+00:00",
    "category": "On My Mind",
    "mood": 3,
    "engagement": 2
  },
  {
    "id": "p40",
    "t": "2026-07-16T21:53:54.026441+00:00",
    "category": "On My Mind",
    "mood": 5,
    "engagement": 6
  },
  {
    "id": "p41",
    "t": "2026-07-16T22:45:33.388887+00:00",
    "category": "On My Mind",
    "mood": 6,
    "engagement": 8
  },
  {
    "id": "p42",
    "t": "2026-07-17T03:03:49.964155+00:00",
    "category": "Sports",
    "mood": 9,
    "engagement": 10
  },
  {
    "id": "p43",
    "t": "2026-07-17T04:39:20.153474+00:00",
    "category": "Eat & Drink",
    "mood": 8,
    "engagement": 8
  },
  {
    "id": "p44",
    "t": "2026-07-17T16:35:09.13524+00:00",
    "category": "On My Mind",
    "mood": 6,
    "engagement": 7
  },
  {
    "id": "p45",
    "t": "2026-07-17T18:50:12.772141+00:00",
    "category": "On My Mind",
    "mood": 4,
    "engagement": 4
  },
  {
    "id": "p46",
    "t": "2026-07-17T20:25:03.397943+00:00",
    "category": "On My Mind",
    "mood": 3,
    "engagement": 1
  },
  {
    "id": "p47",
    "t": "2026-07-17T21:06:03.519463+00:00",
    "category": "Work",
    "mood": 5,
    "engagement": 6
  },
  {
    "id": "p48",
    "t": "2026-07-17T22:36:20.83616+00:00",
    "category": "On My Mind",
    "mood": 8,
    "engagement": 9
  },
  {
    "id": "p49",
    "t": "2026-07-17T23:17:52.237513+00:00",
    "category": "On My Mind",
    "mood": 7,
    "engagement": 9
  },
  {
    "id": "p50",
    "t": "2026-07-18T00:41:22.015371+00:00",
    "category": "On My Mind",
    "mood": 9,
    "engagement": 9
  },
  {
    "id": "p51",
    "t": "2026-07-18T03:08:02.58636+00:00",
    "category": "On My Mind",
    "mood": 9,
    "engagement": 9
  },
  {
    "id": "p52",
    "t": "2026-07-20T16:53:45.726868+00:00",
    "category": "On My Mind",
    "mood": 6,
    "engagement": 6
  },
  {
    "id": "p53",
    "t": "2026-07-20T17:42:33.959832+00:00",
    "category": "On My Mind",
    "mood": 9,
    "engagement": 8
  },
  {
    "id": "p54",
    "t": "2026-07-20T19:50:14.691857+00:00",
    "category": "On My Mind",
    "mood": 2,
    "engagement": 1
  },
  {
    "id": "p55",
    "t": "2026-07-20T22:29:26.024353+00:00",
    "category": "Watch",
    "mood": 4,
    "engagement": 4
  },
  {
    "id": "p56",
    "t": "2026-07-20T23:58:29.291692+00:00",
    "category": "Eat & Drink",
    "mood": 8,
    "engagement": 8
  },
  {
    "id": "p57",
    "t": "2026-07-21T02:08:25.964992+00:00",
    "category": "Eat & Drink",
    "mood": 6,
    "engagement": 8
  },
  {
    "id": "p58",
    "t": "2026-07-21T15:30:46.4361+00:00",
    "category": "Work",
    "mood": 5,
    "engagement": 8
  },
  {
    "id": "p59",
    "t": "2026-07-21T18:53:17.966981+00:00",
    "category": "Work",
    "mood": 6,
    "engagement": 7
  },
  {
    "id": "p60",
    "t": "2026-07-21T20:16:49.421025+00:00",
    "category": "Work",
    "mood": 4,
    "engagement": 7
  },
  {
    "id": "p61",
    "t": "2026-07-22T16:04:50.92182+00:00",
    "category": "Work",
    "mood": 4,
    "engagement": 8
  },
  {
    "id": "p62",
    "t": "2026-07-22T19:45:03.434733+00:00",
    "category": "On My Mind",
    "mood": 2,
    "engagement": 1
  },
  {
    "id": "p63",
    "t": "2026-07-22T21:03:34.549823+00:00",
    "category": "Eat & Drink",
    "mood": 8,
    "engagement": 9
  },
  {
    "id": "p64",
    "t": "2026-07-22T21:54:43.847482+00:00",
    "category": "Watch",
    "mood": 7,
    "engagement": 7
  },
  {
    "id": "p65",
    "t": "2026-07-23T01:44:09.631212+00:00",
    "category": "On My Mind",
    "mood": 7,
    "engagement": 8
  },
  {
    "id": "p66",
    "t": "2026-07-23T16:47:38.137844+00:00",
    "category": "On My Mind",
    "mood": 4,
    "engagement": 4
  },
  {
    "id": "p67",
    "t": "2026-07-24T17:49:21.375908+00:00",
    "category": "On My Mind",
    "mood": 5,
    "engagement": 7
  }
];
